FROM python:3.12-slim

WORKDIR /app

COPY python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir kafka-python

COPY python/kafka_analyzer.py .

CMD ["python", "kafka_analyzer.py"]
