FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

ENV GOTOOLCHAIN=auto
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o collector ./cmd/collector

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/collector .

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["./collector -id $COLLECTOR_ID -etcd $ETCD_ENDPOINTS -meters $TOTAL_METERS -shards $NUM_SHARDS -interval $INTERVAL"]
