FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

ENV GOTOOLCHAIN=auto
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o analyzer ./cmd/analyzer

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/analyzer .

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["./analyzer -etcd $ETCD_ENDPOINTS -interval $INTERVAL -window $WINDOW"]
